# Generated by Django 5.1.5 on 2026-05-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_default_staff'),
        ('myapp', '0006_dutyschedule_order_orderitem'),
    ]

    operations = [
    ]
